### ISSUE TITLE
[REQUEST] Please change shader.

### ISSUE THREAD

**Issue by akronman1** [BoredBean/TouhouCompany#1]
Please change this crap default shader into [Toon Shader](https://github.com/Unity-Technologies/com.unity.toonshader) please
These materials looks terrible
![image](https://github.com/BoredBean/SekibankiSpringMan/assets/38999757/0c6eefcc-46a6-41dc-b11a-8d0bfe6838e7)

**Comment by BoredBean** [comment]
Sorry for the terrible looking. 
Modeling is way beyond my skill stack and I'm still learning about this, as a beginner. There may be a remastered update someday, but since I have a completely unrelated job, it'll probably take a lot of time. 
Thanks for your advice.

**Comment by akronman1** [comment]
I can help you with this if you send me your project and instruction how to build your asset

**Comment by BoredBean** [comment]
Hi akronman1, glad to hear that you are willing to help!

The "blend" file and the Unity "prefab" file are provided in the prefabs folder.


Here is the link for the original model:
https://mikumikudance.fandom.com/wiki/Sekibanki_(Tenkoro)

This plugin supports importing MMD models into Blender:
https://github.com/absolute-quantum/cats-blender-plugin

Here is a template project for Unity:
https://github.com/EvaisaDev/LethalCompanyUnityTemplate

I followed this instruction and made an assetbundle named "sekibanki":
https://docs.unity3d.com/2022.3/Documentation/Manual/AssetBundles-Workflow.html

AssetRipper is used to extract asserts from the game following this guide:
https://lethal.wiki/dev/overview


The "blender" file and the Unity "prefab" file are provided in the prefab folder.

**Comment by BoredBean** [comment]
Some bones are renamed to fit the original coil-head prefab, such as metarig, spine.xxx, springBone.xxx, bodypart.L and bodypart.R. 
These names shouldn't be changed. 

But others like cloak_xxx, skirt_xxx doesn't matter.

**Comment by BoredBean** [comment]
Hi akronman1, just want to confirm if you are still working on this issue, as I need to make some modifications to the model.

**Comment by akronman1** [comment]
Hi. I currently not working on this issues due no project. I need ready to build project

**Comment by akronman1** [comment]
For contact I living on discord. My discord is "akronman1"

**Comment by BoredBean** [comment]
Maybe the [LethalCompanyUnityTemplate](https://github.com/EvaisaDev/LethalCompanyUnityTemplate) is what you want.
There is nothing else I can provide except my experience.
I just don't think it makes sense to upload the 1.6G template project again in this repository.

Well, It’s a shame I can’t access Discord stably most of the time though I have an account.
I prefer Steam or something else.

**Comment by BoredBean** [comment]
I've tried Toon Shader.
It looks good in Unity but worse in the game.
That's all I can do.
![OV8I0$QDQM7GX{~X9 @DAJD](https://github.com/BoredBean/TouhouEnemyModels/assets/18239170/8466b33f-69dd-4b7a-aa34-2e4ee96b528f)
![_NMGR@4BX9 `Y_SVAV%((UV](https://github.com/BoredBean/TouhouEnemyModels/assets/18239170/955c6e53-bf2f-45a1-b8b3-8d9daf079efc)

**Comment by akronman1** [comment]
idk, im playing without post-processing

**Comment by akronman1** [comment]
So can you publish version with this variant?

**Comment by BoredBean** [comment]
> So can you publish version with this variant?

That view (check the picture) is unacceptable to me so Toon Shader won't be applied.
﻿
I will still optimize the texture. It will be released later today.
