### ISSUE TITLE
Unexpected Behavior with CoilHeadStare Installed +more

### ISSUE THREAD

**Issue by Keegrwocky** [BoredBean/TouhouCompany#2]
### I was using **ControlCompany** to test my modpack and decided to test the compatibility between this and a few mods. My findings are as follows:
_**NOTE:** Couldn't figure out where else to put this so I hope its ok I put it here._

- **CoilHeadStare** kind of works but it seems to think its eyes are on the top of its head.
![Screenshot (21)](https://github.com/BoredBean/SekibankiSpringMan/assets/47952933/92b16e61-478a-4ce5-9765-ee8fac855cb0)
- **SassyCoilhead** causes the model stop animating once the effect of the mod kicks in.
![Screenshot (17)](https://github.com/BoredBean/SekibankiSpringMan/assets/47952933/075b67bc-fe80-4bb7-9a89-3a8f720cc6e7)
- **VougeHeads** makes the model not animate at all.
![Screenshot (16)](https://github.com/BoredBean/SekibankiSpringMan/assets/47952933/399beeb5-3da5-49e3-b664-15a9d2540edc)

**Comment by Keegrwocky** [comment]
I wasn't able to test it, but I think i figured out how to solve the issue with **CoilHeadStare**.
[CoilHeadStare Fix.zip](https://github.com/BoredBean/SekibankiSpringMan/files/14716652/CoilHeadStare.Fix.zip)

**Comment by Keegrwocky** [comment]
It should be pretty easy to figure out what changes I made if you check the list/guide on the [CoilHeadStare Mod Page](https://thunderstore.io/c/lethal-company/p/TwinDimensionalProductions/CoilHeadStare/).

**Comment by BoredBean** [comment]
Hi Keegrwocky,

Well, I haven't tested these yet, but I think I may explain a few things. 

The animations and poses, so as that creepy spinning head I think, are based on the bones of the original coil-head model. 

I will be checking back later this month.

Thanks for your information.

**Comment by Keegrwocky** [comment]
No problem! Happy to help!

By the way, if the edits I made don't fix it then I know what needs to be changed. To put it simply, "HeadTarget" needs to be the last child of "springBone.002" in the hierarchy. I didn't do it cuz if it affected an animation I wouldn't be able to fix it, since I don't have the animations.

**Comment by BoredBean** [comment]
1. CoilHeadStare: I will fix the bones.

2. [SassyCoilhead](https://github.com/GhoulMage/SassyCoilhead) has an issue itself. You can check the issue here: [Coilhead isn't dancing at all](https://github.com/GhoulMage/SassyCoilhead/issues/2) 
**You can fix it by placing the files in the correct path as shown.** But it looks weird since the original coil-head model has fewer bones.
![image](https://github.com/BoredBean/SekibankiSpringMan/assets/18239170/b8809592-24ea-4276-b9e0-9ae83e6bcc8a)

3. VougeHeads: Something's wrong with the animator. I can fix it, but I don't know why.

**Comment by BoredBean** [comment]
All fixed at v0.8.2.
Due to the difference in body shape between the two models, there may be some distortion when setting the animations of _VougeHeads_. (can't fix)
