### ISSUE TITLE
Marisa Lootbug

### ISSUE THREAD

**Issue by Zeta-Arcade** [BoredBean/TouhouCompany#3]
I dont know if you thought of this or not, but this could be a good one!
<img src="https://github.com/BoredBean/TouhouEnemyModels/assets/40453201/86f5cd73-2ceb-4fb5-b7cf-cf3b6efcd7ad" width=25% height=25%>
![image](https://github.com/BoredBean/TouhouEnemyModels/assets/40453201/018ae2e3-2096-4908-baf4-f664a4801f87)

It would go very well with the [Scarlet Devil Mansion](https://thunderstore.io/c/lethal-company/p/Alice/ScarletDevilMansion/) interior mod!

**Comment by BoredBean** [comment]
Nice one.

I have actually thought about this.

She is coming soon.

**Comment by lemniskett** [comment]
This would be really funny

**Comment by BoredBean** [comment]
Released at v0.9.2
