### ISSUE TITLE
Please make volume adjustable

### ISSUE THREAD

**Issue by cmtwelve** [BoredBean/TouhouCompany#4]
Can you make the volume for the music/themes adjustable? They're kind of loud in my opinion, but everyone has different preferences.

**Comment by BoredBean** [comment]
Could you please identify the specific music, or all of them?

I'm afraid not all clips of the music are configurable, since some of them are just replacements of the original audios.

There will be some volume settings, but probably not all of them will work.

**Comment by cmtwelve** [comment]
All of them, it's not as noticeable in singleplayer, but when playing with friends it becomes extremely hard to communicate with each other when the music plays. The best example, and what my group has had an issue with, is Suika hurting our ears when she's charging at the ship. It's very common to be hiding from a giant in there, and having music blasting in your ears so loud that it becomes hard to talk during that entire duration gets kind of annoying after a while. 

You do have a point, since they're controlled by the game it may be kind of hard to adjust the volume. I'm not super familiar with how all that works unfortunately, but I _have_ been able to make a sound replacement mod with loaforcsSoundAPI, so I might be able to help a bit with that. I'm not sure if it has volume options though... I'd have to check with the dev. 

As a side note, if there's something else I can help with, let me know. I'm not super experienced myself, but I may have a friend that can help with modeling or whatever you need help with on the Utsuho Mech.

**Comment by BoredBean** [comment]
You can disable the music before I get it fixed. 

The only problem is that there is still too much work to do, but I don't have enough time.
It would be easier and faster if someone else could join.
(I just messed up my assets as a clumsy novice yesterday)

Never mind. Glad to see people using this mod.

**Comment by cmtwelve** [comment]
Yeah, I may go ahead and do that. I understand your situation. The more you practice the better you'll get, I believe in you. And there's certainly people who use it, Touhou has one of the biggest fanbases in the world.

**Comment by BoredBean** [comment]
I tried to fix it, if it doesn't work we can try again.
