### ISSUE TITLE
SUGGESTION / I heard you stopped updating it so I've come up with an idea that might make you want to return.

### ISSUE THREAD

**Issue by rampa93** [BoredBean/TouhouCompany#6]
Wanted to talk about hoarder bug idea actually.
It must've been funnier if it just had marisa's hair and her hat on default hoarder bug model.
<img width="810" alt="일러스트43" src="https://github.com/BoredBean/TouhouCompany/assets/167766171/75c86364-e8ea-41f2-9d2d-5ddc8cb7d484">
like this.
Hope I could help you deal with solitary.
I know nothing about modeling tho.
<img width="2034" alt="일러스트28" src="https://github.com/BoredBean/TouhouCompany/assets/167766171/babfc91e-8b70-4684-8851-6c8f8fee9d80">

**Comment by BoredBean** [comment]
Great painting! Thank you.

Lacking feedback, I sometimes doubt whether I am doing something meaningless. 
It's feeling better having you here.
![image](https://github.com/BoredBean/TouhouCompany/assets/18239170/d28f4f11-ecfa-4a0f-8d68-c64dffb5973d)

In fact, I am trying some other ideas.
That's the reason I changed the name of this project to TouhouCompany.
There are too many things I want to add to the game.
But I can't implement all of them independently.
So I have to hit the pause button on this one. 

![image](https://github.com/BoredBean/TouhouCompany/assets/18239170/d7af909d-a774-4e99-b54f-26845c3ddaec)

Another fact is that this mod has reached 200M+.
I'd better make it smaller before continuing.
But I don't have any clues right now.

**Comment by BoredBean** [comment]
Released at tag v0.9.5.
